#!/usr/bin/env node
// Generates TypeScript types (openapi-typescript) and Zod validators
// (json-schema-to-zod) from packages/contracts/openapi/*.yaml.
// `--check` regenerates in memory and fails if the committed files differ.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { parse } from 'yaml';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPECS = ['core-api', 'ai-service'];
const HEADER = '// @generated by packages/contracts/scripts/generate-ts.mjs. DO NOT EDIT.\n// Source: packages/contracts/openapi/';
const REF = /^#\/components\/schemas\/([A-Za-z0-9_]+)$/;

function refsOf(node, out = new Set()) {
  if (Array.isArray(node)) node.forEach((n) => refsOf(n, out));
  else if (node && typeof node === 'object') {
    if (typeof node.$ref === 'string') {
      const m = REF.exec(node.$ref);
      if (m) out.add(m[1]);
    }
    Object.values(node).forEach((v) => refsOf(v, out));
  }
  return out;
}

function topoSort(schemas) {
  const order = [];
  const state = new Map();
  const visit = (name) => {
    if (state.get(name) === 'done') return;
    if (state.get(name) === 'visiting') throw new Error(`recursive schema ${name} is not supported`);
    state.set(name, 'visiting');
    for (const dep of [...refsOf(schemas[name])].sort()) visit(dep);
    state.set(name, 'done');
    order.push(name);
  };
  Object.keys(schemas).sort().forEach(visit);
  return order;
}

/** OpenAPI 3.1 `const` and `type: [x, 'null']` are JSON Schema; drop OpenAPI-only keywords. */
function clean(node) {
  if (Array.isArray(node)) return node.map(clean);
  if (!node || typeof node !== 'object') return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === 'format' && v === 'uuid') out.format = 'uuid';
    else if (k.startsWith('x-')) continue;
    else out[k] = clean(v);
  }
  return out;
}

function zodFor(spec) {
  const schemas = spec.components?.schemas ?? {};
  const lines = [];
  for (const name of topoSort(schemas)) {
    const code = jsonSchemaToZod(clean(schemas[name]), {
      module: 'none',
      parserOverride: (schema) => {
        const m = typeof schema.$ref === 'string' ? REF.exec(schema.$ref) : null;
        return m ? m[1] : undefined;
      },
    });
    lines.push(`export const ${name} = ${code.trim().replace(/;$/, '')};`);
    lines.push(`export type ${name} = z.infer<typeof ${name}>;`);
    lines.push('');
  }
  return `import { z } from 'zod';\n\n${lines.join('\n')}`;
}

async function render(name) {
  const yamlText = readFileSync(join(root, 'openapi', `${name}.yaml`), 'utf8');
  const spec = parse(yamlText);
  const ast = await openapiTS(spec, { exportType: true, alphabetize: true, immutable: true });
  return {
    [`generated/ts/${name}.ts`]: `${HEADER}${name}.yaml\n\n${astToString(ast)}`,
    [`generated/ts/${name}.zod.ts`]: `${HEADER}${name}.yaml\n/* eslint-disable */\n${zodFor(spec)}`,
  };
}

const check = process.argv.includes('--check');
let drift = 0;
for (const name of SPECS) {
  for (const [rel, content] of Object.entries(await render(name))) {
    const file = join(root, rel);
    if (check) {
      let current = '';
      try {
        current = readFileSync(file, 'utf8');
      } catch {
        /* missing counts as drift */
      }
      if (current !== content) {
        drift++;
        console.error(`drift: ${rel} is out of date. Run \`pnpm contracts:generate\`.`);
      }
    } else {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, content);
      console.log(`wrote ${rel}`);
    }
  }
}
if (drift > 0) process.exit(1);
if (check) console.log('contracts: generated TypeScript and Zod are up to date');
