"""Generate Pydantic v2 models from packages/contracts/openapi/*.yaml.

Usage: uv run python packages/contracts/scripts/generate_pydantic.py [--check]

--check regenerates into a temp dir and exits 1 if committed output differs.
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "generated" / "python" / "invoiceiq_contracts"
SPECS = {"core_api": "core-api.yaml", "ai_service": "ai-service.yaml"}
HEADER = "# @generated by packages/contracts/scripts/generate_pydantic.py. DO NOT EDIT."


def generate(dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for module, spec in SPECS.items():
        target = dest / f"{module}.py"
        subprocess.run(  # noqa: S603 - fixed argv, no shell
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(ROOT / "openapi" / spec),
                "--input-file-type",
                "openapi",
                "--output",
                str(target),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.11",
                "--use-standard-collections",
                "--use-union-operator",
                "--use-schema-description",
                "--field-constraints",
                "--enum-field-as-literal",
                "one",
                "--disable-timestamp",
                "--custom-file-header",
                HEADER,
                "--formatters",
                "ruff-format",
            ],
            check=True,
        )
    (dest / "__init__.py").write_text(
        f'{HEADER}\n"""Pydantic models for the InvoiceIQ service contracts."""\n'
    )
    (dest / "py.typed").write_text("")


def main() -> int:
    if "--check" not in sys.argv:
        if OUT.exists():
            shutil.rmtree(OUT)
        generate(OUT)
        print(f"wrote {OUT.relative_to(ROOT.parents[1])}")
        return 0
    # Generate inside the repo so the formatter picks up the same ruff config.
    with tempfile.TemporaryDirectory(dir=ROOT, prefix=".gen-check-") as tmp:
        fresh = Path(tmp) / "invoiceiq_contracts"
        generate(fresh)
        cmp = filecmp.dircmp(fresh, OUT, ignore=["__pycache__"]) if OUT.exists() else None
        if cmp is None or cmp.left_only or cmp.right_only or cmp.diff_files:
            detail = "missing" if cmp is None else f"{cmp.left_only + cmp.right_only + cmp.diff_files}"
            print(f"drift: generated Pydantic models are out of date ({detail}).", file=sys.stderr)
            print("Run `make contracts`.", file=sys.stderr)
            return 1
        _, mismatch, errors = filecmp.cmpfiles(
            fresh, OUT, sorted(p.name for p in fresh.iterdir()), shallow=False
        )
        if mismatch or errors:
            print(f"drift: {mismatch + errors} differ. Run `make contracts`.", file=sys.stderr)
            return 1
    print("contracts: generated Pydantic models are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
