/**
 * Writes packages/contracts/catalog/reason-codes.json from the domain catalog so
 * Python tooling (data/, evals/) can read allowed outcomes without re-declaring
 * them. `--check` fails if the committed file is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { INVOICE_STATES, REASON_CATALOG, REASON_CODES, TRANSITIONS } from '../src/domain/index.js';

export function renderCatalog(): string {
  const catalog = {
    $comment: 'Generated by services/core-api/scripts/export-catalog.ts. DO NOT EDIT.',
    states: INVOICE_STATES,
    transitions: TRANSITIONS,
    reasonCodes: Object.fromEntries(
      REASON_CODES.map((code) => {
        const r = REASON_CATALOG[code];
        return [code, { source: r.source, severity: r.severity, allowedOutcomes: r.allowedOutcomes }];
      }),
    ),
  };
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

export const CATALOG_PATH = join(import.meta.dirname, '..', '..', '..', 'packages', 'contracts', 'catalog', 'reason-codes.json');

if (process.argv[1] !== undefined && import.meta.filename === process.argv[1]) {
  const rendered = renderCatalog();
  if (process.argv.includes('--check')) {
    if (readFileSync(CATALOG_PATH, 'utf8') !== rendered) {
      console.error('drift: packages/contracts/catalog/reason-codes.json is stale. Run `pnpm --filter @invoiceiq/core-api catalog`.');
      process.exit(1);
    }
    console.log('catalog: reason-codes.json is up to date');
  } else {
    writeFileSync(CATALOG_PATH, rendered);
    console.log('wrote packages/contracts/catalog/reason-codes.json');
  }
}
